# Generated by Django 2.2 on 2019-10-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
