# Generated by Django 2.2 on 2019-10-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nino', '0002_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Motivo_ingreso',
                'verbose_name_plural': 'Motivo_ingresos',
            },
        ),
    ]
