# Generated by Django 2.2 on 2019-10-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0004_registro_idioma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivo_ingreso',
            options={'verbose_name': 'Motivo_Ingreso', 'verbose_name_plural': 'Motivo_Ingresos'},
        ),
    ]
