# Generated by Django 2.2 on 2019-10-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0006_registro_enfermedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Nivel_nutricion',
                'verbose_name_plural': 'Nivel_nutricions',
            },
        ),
    ]
