# Generated by Django 2.2 on 2019-10-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0008_registro_etnia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_Enfermedades',
            new_name='Registro_Enfermedade',
        ),
        migrations.AlterModelOptions(
            name='registro_enfermedade',
            options={'verbose_name': 'Registro_Enfermedade', 'verbose_name_plural': 'Registro_Enfermedades'},
        ),
    ]
