# Generated by Django 2.2 on 2019-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0009_auto_20191008_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_nutricion',
            name='estado',
            field=models.BooleanField(blank=True),
        ),
    ]
