# Generated by Django 2.0.13 on 2019-10-09 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0010_auto_20191008_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivo_ingreso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='nivel_nutricion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registro_enfermedade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registro_etnia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registro_idioma',
            name='estado',
        ),
    ]
